INSERT INTO destinations (location, cost_pp, activity_genre, activity_type, activity_title, number_people, kid_friendly) 
VALUES ("London", 5000, "abroad", "cultural", "museums", 2, true), 
("Bali", 5000, "abroad", "adrenaline","diving", 1, false), 
("Austin", 750, "city", "partying", "concert", 4, true),
("Denver", 300, "city", "partying", "sporting event", 2, true),
("San Diego", 750, "beach", "active", "surfing", 2, false),
("Taos", 300, "mountains", "active", "skiing", 4, true),
("Thailand", 1000, "abroad", "volunteering", "charity work", 1, false),
("Chicago", 750, "city", "cultural", "museums", 2, true),
("Glacier National Park", 300, "mountains", "active", "hiking", 3, true),
("Sicily", 3000, "beach", "cultural", "cooking classes", 1, false),
("Morocco", 10000, "city", "active", "hiking", 2, false),
("Scotland", 10000, "mountains", "active", "biking", 6, false),
("Ibiza", 5000, "beach", "partying", "full moon party", 2, false),
("Grand Canyon", 1000, "mountains", "active", "rafting", 10, true),
("Parent's House", 0, "staycation", "partying", "pinochle", 1, false),
("Under the Bridge", 0, "staycation", "spiritual", "sleeping", 1, false),
("Swap houses with a friend", 0, "staycation", "cultural", "take-out/Netflix", 4, true),
("Swap houses with a stranger", 750, "city", "cultural", "delivery/movie theater", 2, false),
("Anywhere in Kansas", 300, "staycation", "partying", "the bars", 2, false),
("Florida Keys", 5000, "beach", "active", "fishing", 4, true),
("Nepal", 10000, "abroad", "adrenaline", "climb Mt. Everest", 2, false),
("Alaska", 5000, "mountains", "active", "ice-fishing", 4, true),
("New York", 3000, "city", "cultural", "sight-seeing", 4, true),
("Dubai", 10000, "abroad", "adrenaline", "eco tours", 8, true),
("Garden of the Gods in Colorado Springs", 1000, "city", "active", "rock climbing", 6, false),
("Bora Bora", 5000, "abroad", "adrenaline", "jet boating", 2, false),
("Fiji", 3000, "abroad", "active", "island tour", 5, true),
("In Your town", 300, "city", "cultural", "Movie Theater", 1, true),
("Utah", 750, "mountains", "active", "Exploring Moab", 1, true),
("New Orleans", 750, "city", "volunteering", "Habitat for Humanity", 1, true),
("San Francisco", 1000, "city", "partying", "Food/Bar Crawl", 1, false),
("San Diego", 1000, "city", "cultural", "San Diego Zoo", 1, true),
("Antartica", 10000, "abroad", "adrenaline", "Antartic Exploration", 1, false),
("Iceland", 10000, "abroad", "active", "Viewing Northern Lights", 1, false),
("Boston", 750, "city", "partying", "Going to Fenway Park", 1, true),
("Las Vegas", 750, "city", "partying", "Going to the Casinos", 1, false),
("Giraffe Manor", 5000, "abroad", "active", "African safari, lodging at the famouse Giraffe Manor", 1, true),
("Galapagos", 10000, "abroad", "adrenaline", "Live aboard dive trip", 1, false),
("Canadian Rockies", 3000, "mountains", "adrenaline", "heli-skiing", 1, false),
("In your town", 300, "city", "active", "Sky Zone - trampolines", 1, true),
("Florida", 1000, "city", "active", "Disney World", 1, true),
("Cedar Point", 750, "city", "adrenaline", "Roller Coaster Amusement Park", 1, true),
("Local library", 0, "staycation", "cultural", "reading", 1, true),
("Mosque of Mecca", 3000, "abroad", "spiritual", "worship", 2, true),
("Neighborhood exploration", 0, "staycation", "cultural", "sight-seeing", 5, true),
("Go visit your nearest neighbor and say Hi!", 0, "staycation", "spiritual", "Meeting People", 1, true),
("Dollar Tree", 300, "staycation", "partying", "decorating a room in your house for fun", 1, true),
("The Vatican", 5000, "abroad", "spiritual", "pilgrimage", 2, true),
("Pilgrimage to Jerusalem", 3000, "abroad", "spiritual", "worship", 1, true),
("Internet Archives Online", 0, "staycation", "cultural", "Pick a documentry and learn something new", 1, true),
("Tour Around the World", 10000, "abroad", "active", "sight-seeing", 4, true),
("Local Park", 0, "staycation", "adrenaline", "go play at your local park", 5, true),
("Backyard Oasis and Pool", 10000, "staycation", "partying", "Hire someone to build a swimming pool oasis in your backyard and play", 5, true),
("Go To Chruch", 0, "staycation", "spiritual", "worship", 2, true),
("Big Buddha", 5000, "abroad", "spiritual", "worship", 2, true);

SELECT * FROM destinations;
